package com.app.Repository;

import com.app.Model.Song;
import org.springframework.data.jpa.repository.JpaRepository;

/**
 * Repository interface for performing CRUD operations on Song entities.
 *
 * This interface extends JpaRepository, providing built-in methods for 
 * interacting with the database, such as saving, finding, deleting, and updating Song records.
 *
 * The implementation will be automatically generated by Spring Data JPA at runtime.
 */
public interface SongRepository extends JpaRepository<Song, Long> {
}